In [144]:
import numpy as np

In [145]:
#Ejercicio 1: Aritmética
print(2*3-1)
print(2**3)
print(3-2**4)
print(3*2**4)
print((3*2)**4)
print(3**4-3)
print(5e-3)
print(22/5)
print(22//5) #devuelve la parte entera del cociente
print(22%5) #devuelve el resto de la division
print(8/4*2)
print(2+3.0)
print(2j+3)
print((1j)**2)


5
8
-13
48
1296
78
0.005
4.4
4
2
4.0
5.0
(3+2j)
(-1+0j)


In [146]:
#Ejercicio 2
type(22/5)
type(22//5)
type(8/4*2)
type(2+3.0)
#Te tira el tipo de dato de los resultados de esas operaciones

float

In [147]:
#Ejercicio 3: Declaración de variables
x=2
print(x)
print(x**4)
print(x)
x=3*x
print(x)
y=x
print(y)
y=1
print(y)
print(x)
del(x)
x
#El del te elimina la variable

2
16
2
6
6
1
6


NameError: name 'x' is not defined

In [ ]:
#Ejercicio 4: Operadores lógicos
2==3
type(2==3)
2!=3
type(2!=3)
2<3
type(2<3)
not 2<3
type(not 2<3)
2!=3 and 1<4
#Etc,etc: son todos datos de tipo bool o booleanos, es decir que expresan un valor de verdad (true o false)

True

In [ ]:
#Ejercicio 5: Constantes y funciones básicas
np.pi
np.e
np.inf
np.exp(2)
np.log(10)
#el log siempre es ln
np.log(np.e)
np.sin(180)
np.sin(np.pi)
np.cos(np.pi)

-1.0

In [ ]:
#Ejercicio 6: Creación de vectores
v=np.array([3,4,7,11,13])
v
v[1]
#Los corchetes señalan el lugar del vector que quiero arrancando desde el cero y el lugar -1 es el ultimo
v[1:4]
#Desde-hasta excluyendo el ultimo lugar que indico
v[1]=100
v
np.arange(9) #vector desde el cero hasta el nueve excluido
np.arange(2,9) #lo mismo pero arranco en el dos
np.arange(2,9,3) #lo mismo moviendome de a 3 numeross
np.linspace(0,1,3) #te divide el intervalo (0,1) en tres partes iguales
np.repeat(0,5) #te repite 5 veces el cero
np.repeat(v,5) #lo mismo pero con cada coordenada del vector
np.tile(v,5) #te concatena 5 veces el vector

array([  3, 100,   7,  11,  13,   3, 100,   7,  11,  13,   3, 100,   7,
        11,  13,   3, 100,   7,  11,  13,   3, 100,   7,  11,  13])

In [ ]:
#Ejercicio 7: Creación de matrices
M=np.array([[3,4,6],[7,11,13]]) #crea la matriz, cada vector es una fila
M
M[1,1] #te indexa la matriz con el lugar a11 el [0,0]
M[1,:] #te da la fila 1, si pongo al reves te da la columna 1
M[0,0]=10
M
np.tile(M,(4,2)) #pone cada fila doble, como concatenadas y a su vez concatena la matriz completa 4 veces
np.eye(4) #la canonica :)
A=np.tile(4,(2,3)) #matriz de 2x3 solo con 4
np.concatenate((M,A),axis=0) #concatena las matrices una arriba de otra, si pongo axis=1 es una al lado de la otra
np.concatenate((M,A),axis=1) #o sea, combina la fila 0 de M con la de A como un mismo vector y lo mismo la fila 1

array([[10,  4,  6,  4,  4,  4],
       [ 7, 11, 13,  4,  4,  4]])

In [ ]:
#Ejercicio 8: Operación entre vectores y matrices
M=np.array([[1,2],[3,4]])
N=np.array([[5,6],[7,8]])
P=np.array([[1,2,3],[1,2,3]])
v=np.array([1,2])
w=np.array([3,4])
#Comandos
M+N
M+2 #mas dos en cada lugar
M*2 #por dos en cada lugar
M**2 #al cuadrado en cada lugar
np.linalg.matrix_power(M,2) #potencias de la matriz M
M*N #multiplica lugar a lugar, o sea: m11xn11 y asi pero nada mas
M@N #producto matricial
M*v #En cada fila hace como el de M*N
M@v #el de toda la vida
v*w #lugar a lugar
v@w #el de toda la vida
P.T #traspuesta
v@(w.T)
np.outer(v,w) #matriz formada por v[0]*w y v[1]*w

array([[3, 4],
       [6, 8]])

In [ ]:
#Ejercicio 9 
M=np.array([[1,2],[3,4]])
N=M
N[1,1]=0
N
M
#M no debería quedarse igual? Porque yo solo cambié la N

array([[1, 2],
       [3, 0]])

In [ ]:
#Ejercicio 10 
M=np.array([[1,2],[3,4]])
N=np.copy(M)
N[1,1]=0
N
M
#Respecto a la duda del ejercicio anterior: NO, ya que son como la misma variable, en cambio aca N es una copia.
#Esto tenia un nombre en ip que no me lo acuerdo pero basicamente en el 9 reescribo la misma celda de memoria, en el 10 "creo una nueva celda"

array([[1, 2],
       [3, 4]])

In [ ]:
#Ejercicio 11
def f1(x):
    print(x**2+5*x)
def f2(x):
    print(np.cos(x)+np.sin(x))
def f3(v):
    print(v[0]+v[-1])
def f4(v,w):
    print(np.cross(v,w))
def f5(k):
    if k%2==0:
        return True
    else:
        return False
def f6(k):
    if k%2==0:
        return 1
    else:
        return 0
def f7(x):
    if x>=0:
        return x
    else:
        return -x
def f8(M):
    if len(np.shape(M))==1:
        return 0
    else:
        return 1
def f9(a,b):
    if a>b:
        return 1
    if a<b:
        return -1
    else:
        return 0
def f10(v,w):
    if len(v)==len(w):
        return v+w
    else:
        return np.repeat(0,min(len(v),len(w)))
#v1=np.array([1,2,3])
#w1=np.array([4,5,6])  No olvidar que los tengo que definir como array para que me los sume bien
#f10(v1,w1)

array([5, 7, 9])

Ejercicio 12: estudiar los siguientes programas y decidir qué hacen

a) def f(n):
       y=np.repeat(0,n)
       for i in np.arrange(n):
           y[i]=(i+1)**2
       return y

Dado un vector y de tamaño n con ceros en todas sus coordenadas, voy recorriendo cada lugar de ese vector con el for.
En cada lugas i ahora voy a poner el numero de ese lugar más uno y elevo todo al cuadrado. Quedaría una cosa así [1,4,9,...,n**2]

b) def f(g,v):
       n=len(v)
       y=np.repeat(0,n):
       for i in np.arrange(n):
           y[i]=g(v[i])
       return y

Dada una función g y un vector v, definimos n como la longitud de v y a y como en el item a). Nuevamente recorremos toda la longitud de y (que es la misma que la del vector v) utilizando el for pero ahora en cada coordenada vamos a aplicarle g a la coordenada analoga del vector v.

c) def f(n):
       y=1
       for i in np.arrange(n):
           y=y*(i+1)
       return y

Dado un numero natural n, definimos y=1 y para cada numero desde el 0 hasta el n-1 vamos a repetir la operacion multiplicar y por ese numero mas uno.

d) def f(v):
       n=len(v)
       y=0
       for i in np.arrange(n):
           if v[i]==0:
               y=y+1
       return y

Dado un vector v de longitud n definimos y=0. Para cada numero del 0 al n-1: si el vector en esa posicion es un cero, le sumamos un 1 a y. Así recorremos todo el vector sumando siempre que haya un cero.

e) def f(n,k):
       i=0
       while (i+n<=k):
           i=i+n
       return i

Dados dos numeros naturales n y k, definimos i=0. Nos fijamos si i+n es menor o igual a k; si lo es redefinimos i=i+n y repetimos el proceso. Cuando ya no se cumpla la condición, la funcion nos devuelve el ultimo valor que le dimos a i.

f) def f(v,k):
       i=0
       while (v[i]<=k):
           i=i+1
       return v[i]

Dado un vector v y un número natural k, definimos i=0. Nos fijamos si el vector en el lugar i es menor o igual a k; si lo es redefinimos i=i+1 y repetimos el proceso. Cuando ya no se cumpla la condición, la función devuelve la posición del vector que no la cumple. (La función nos el primer lugar del vector que es mayor estricto que k)

In [183]:
#Ejercicio 13
#a)
def traza (M):
    tr=0
    n=(len(M))
    for i in np.arange(n):
        tr=tr+M[i,i]
    return tr

M0=np.array([[1,2,3],[1,2,3],[1,2,3]])
traza(M0)

#b)
def vsuma(n):
    v=np.repeat(0,n)
    for i in np.arange(n):
        if i==0:
            v[i]=1
        else:
            v[i]= i+1+v[i-1]
    return v

vsuma(5)

#c)
def vinvertir(v):
    n=len(v)
    for i in range(0,n//2):
        x=v[i]
        v[i]=v[n-1-i]
        v[n-1-i]=x
    return v

v0=[1,2,3,4,5]
vinvertir(v0)

#d)
def fibo(n):
    if n<=1:
        return n
    else:
        return fibo(n-1) + fibo(n-2)

fibo(12)

#e)
def primo(n):
    i=2
    while i in range(2,n):
        if (n%i)==0:
            return False
        else:
            i=i+1
    return True

primo(59)

#f)
def primerMenor(v,k):
    i=0
    while i in range(0,len(v)-1):
        if v[i]>=k:
            i=i+1
        else:
            return v[i]

v0=np.array([9,7,8,7,8,9,5,6,5,4,3])
primerMenor(v0,6)

#g)
def elemMaxVector(v):
    res=v[0]
    for i in range(len(v)):
        if v[i]>=res:
            res=v[i]
    return res

v0=np.array([2,1,5,3,4,9,0,6,8])
elemMaxVector(v0)

#h)
def elemMaxMatrix(M):
    f=(np.shape(M))[0]
    res=elemMaxVector(M[0, :])
    for i in range(f):
        maxf=elemMaxVector(M[i,:])
        if maxf>res:
            res=maxf
    return res

M0=np.array([[1,2],[7,3],[3,4]])
elemMaxMatrix(M0)
#np.shape([[1,2],[2,3],[3,4]]) devuelve (3,2) por 3 filas y dos columnas

#i)
def dondeMax(v):
    for i in range(len(v)):
        if v[i]==elemMaxVector(v):
            return i

v0=np.array([2,5,4,13,6,8,1])
dondeMax(v0)

6